language: node_js
node_js: 6
branches:
  only: master
script:
- gulp test
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: DbBGk2k2t++HvnQWKcUaqQCu9wVXbb92Ynq8DP9E1CFyv+cTHOSFpraSUoD/jJOIkFKqjAQaxphNw0UA0bE1KtUmN1pjUoBoCmTN+3DsLN+OCGPeym1uQN+wOc7HgIVU5QdaYjPilP1L+YrHpBuw7yEUIOQ/JaoQbo9kCC/HdtApMDIqZucXszZWVzXplNVYV/rSt3ZvaaAb8BHLLJvTgYelIPG+6hFeuJJJUlbCHZ1WXfAGDvTsrJOuPrSC77q4LiIO+ocLQdmnMWtnb2w3o1XlCZ/4z6Jfw3U2g5JZCOBQMTpQIDpQTa9I/6ewbByhz5Tvke3oKwawL36uQEIh5XV5eTg4VNlMyeGs0A0RtdQZzQWJ1bM8SfQBJVpDrxYNp33Uj9p+QxpTNt3KLyY2S0aF/J66UyBqTowsOg26oR0ZZAyZKoiIkPoAbgItLspFwg2jKT5I6010dyNXQ6lfBQLizQl9K3TpAxwYm09ddr+JJmJZc3r4LwswdHPiBhAhDKwaw2DM6hQ9Tm0QAhpfxE8ayondEexX1vVhDHjjwzApTNosfOdqZZFlaf08D5sX84nNLvyvaBwli8vgdCsVwmd2PE6Kd2JT7U+SZXclOjpjk6Dva9WiktD59c6+MVpkYBh9+3XXckSi7ZrfkI0fOQxfF4cnqYQVUYpRg3ieidE=
